name: CI

on: [push]

jobs:
  standard-checks:
    name: Lint and Test Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install packages
        run: npm ci

      - name: Run ESlint
        run: npm run lint:ci

      - name: Run tests
        run: npm run test:ci

      - name: Build and Output Code
        run: npm run build
